// Princess Kingdom Theme Assets
export { default as princessBackground } from './background.svg'
export { default as princessTaskIcon } from './task.svg'
export { default as princessChoresIcon } from './chores.svg'
export { default as princessRewardsIcon } from './rewards.svg'
export { default as princessChildrenIcon } from './Children.svg'
export { default as princessExitIcon } from './Exit.svg'
export { default as princessEditIcon } from './edit.svg'
export { default as princessDeleteIcon } from './delete.svg'
export { default as princessActiveIcon } from './active.svg'
export { default as princessSelectIcon } from './select.svg'
export { default as princessBuyRewardIcon } from './buy-reward.svg'
export { default as princessGiveStarIcon } from './give-star.svg'
// Note: filename is intentionally 'dasboard.svg' based on prior code
export { default as princessDashboardIcon } from './dasboard.svg'
